### ISSUE TITLE
Get top 10 countries basic census data in the DO 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/bigmetadata#101]
- [x] United States of America
- [x] Spain
- [x] United Kingdom
- [x] France
- [x] Canada
- [ ] ~~Germany~~
- [ ] ~~Poland~~
- [ ] ~~Italy~~
- [x] Australia

**Comment by stuartlynn** [comment]
@talos

**Comment by talos** [comment]
* [ ] Brazil
* [ ] Germany (via Eurostat)
* [ ] Italy (via Eurostat)

**Comment by talos** [comment]
Knocking off Poland because it doesn't have very accessible open data.  Checked off Australia, so closing this!
