### ISSUE TITLE
add more zillow data to zillow tasks

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/bigmetadata#11]
- [ ] add more datasets
  - more geographical scales (zip, state, county, neighborhood)
  - make available geometries?
  - renters index
- [ ] include some pre-calculated columns, like
  - change in home value since 2010, 2014, etc.

**Comment by talos** [comment]
There's more we could add, but we've taken care of all datasets for zip.

**Comment by ohasselblad** [comment]
this is done! @talos did it really awesomely
