### ISSUE TITLE
Age breakdowns incomplete

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/bigmetadata#13]
(just ticketing this so we don't forget)
Many of the buckets seem to be missing and the female variants are not there

![screen shot 2016-05-09 at 11 06 30 am](https://cloud.githubusercontent.com/assets/370259/15117587/3f7cb100-15d6-11e6-88c3-27c4dd9dbf1e.png)

**Comment by andrewxhill** [comment]
not a priority pre-launch, but we should return to these breakdowns in a next release

**Comment by talos** [comment]
These were added with https://github.com/CartoDB/bigmetadata/commit/b60f7fd432fcca1db560f71cd84a7ac52336f3f3 and https://github.com/CartoDB/bigmetadata/commit/a45b6cf138e6127dce34bde2f1d8b33b670e5b44, but are not tagged for the catalog yet.

**Comment by talos** [comment]
Everything is now tagged and accessible.
