### ISSUE TITLE
check if congressional districts are in observatory

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/bigmetadata#15]
Looking now i don't see it in the metadata, but it is listed in the catalog. I school districts are also in the catalog but not in the metadata.

https://cartodb.github.io/bigmetadata/catalog/%22tags%22.boundary.html

**Comment by talos** [comment]
Resolved and accessible:

https://observatory.cartodb.com/tables/obs_01b608b3a4ca503ad7acc0b1f84817bc1da3e193/map
