### ISSUE TITLE
CNIG has new descargas portal

### ISSUE THREAD

**Issue by michellemho** [CartoDB/bigmetadata#155]
As of April 3, 2017, CNIG has published a new download portal (see "What's New" in link below). This means the URLs we used before for downloading CNIG geometries don't work. But it looks like the new download portal is still a little buggy. I haven't been able to successfully download the SIANE data again. A lot of the links don't function correctly...

http://centrodedescargas.cnig.es/CentroDescargas/index.jsp

**Comment by javitonino** [comment]
This was already fixed :D
