### ISSUE TITLE
Available boundaries for AU measures not accurate in Catalog

### ISSUE THREAD

**Issue by michellemho** [CartoDB/bigmetadata#170]
@michellechandra had a request for Australia population by postal codes. It appears in the Catalog that this measures is only available for the boundaries Remoteness Areas, Urban Centres and Localities, and Significant Urban Areas. 

![image](https://user-images.githubusercontent.com/12551177/27229998-c0e5421a-527b-11e7-90c7-89be03152521.png)

Suspicious that so few boundaries were available, I ran OBS_GetAvailableGeometries to check what geometries were available for the measurement Total Persons:
```SQL
SELECT * from OBS_GetAvailableGeometries((SELECT ST_SetSRID(ST_Extent(the_geom), 4326)
FROM (select * from section_of_australia) q), NULL, 'au.data.B01_Tot_P_P')
where valid_numer = True;
```

Many more boundaries are available:
![image](https://user-images.githubusercontent.com/12551177/27230471-5c8161e4-527d-11e7-807c-7e903efb8415.png)

Finally, I ran an OBS_GetMeta and OBS_GetData to confirm this measurement really is available for postal codes, and they are!

```SQL
WITH meta AS (SELECT OBS_GetMeta(
ST_makeenvelope(72.2,-55.3,168.2,-9.1, 4326),
'[{"geom_id": "au.geo.POA"},
 {"numer_id": "au.data.B01_Tot_P_P","geom_id": "au.geo.POA"}]'
) meta)
INSERT INTO australia_pop (the_geom, name, population)
SELECT    (data->0->>'value')::Geometry the_geom,
        (data->0->>'geomref') geomref, 
        (data->1->>'value')::Numeric  
FROM OBS_GetData(Array[(ST_makeenvelope(72.2,-55.3,168.2,-9.1, 4326), 1)::geomval],
(SELECT meta FROM meta), false)
```
Dataset returned here: https://team.carto.com/u/michellemho-carto/dataset/michellemho-carto.australia_pop

These available boundaries need to be reflected in the Catalog. The Catalog might be outdated or the there might be an issue with the metawrappers? I'm not sure. I couldn't find anything in the Australia task that might have left certain boundaries out.

**Comment by javitonino** [comment]
This is fixed in the new catalog, that we will be deploying in the coming days. Closing it.
