### ISSUE TITLE
Include clipped tag for the clipped geometries

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#174]
In order to give more metadata and filter possibilities to the clipped geometries we should add a new tag `clipped` or something like that [here](https://github.com/CartoDB/bigmetadata/blob/2dd801558087e5b51fe444d1d94140bc59f14a2b/tasks/us/census/tiger.py#L68)

To know more about clipped geometries, read [this](https://carto.com/blog/tiger-shoreline-clip) post where John explain it

**Comment by michellemho** [comment]
A tag for  `cartographic_boundary` already serves the same purpose [here](https://github.com/CartoDB/bigmetadata/blob/2dd801558087e5b51fe444d1d94140bc59f14a2b/tasks/us/census/tiger.py#L73-L91)

In this section, we add tags called `cartographic_boundary` and `interpolation_boundary`.
`cartographic_boundary` --> everything that is shoreline clipped (and looks good on a map, hence "cartographic")
`interpolation_boundary` --> clipped boundaries that are _full_ coverage of the country/region

**Comment by ethervoid** [comment]
Maybe we should include only clipped geometries on the US numerator? For example for `us.bls.avg_wkly_wage_10` we return this `geoms`:
```
 {us.census.tiger.county,us.census.tiger.county_clipped}
```
and maybe we should return?:
```
 {us.census.tiger.county_clipped}
```

**Comment by michellemho** [comment]
Agreed, we should only use clipped boundaries for TIGER data. All of those are tagged with `cartographic_boundary`. You can pass the tag into the `filter_tags` in OBS_GetAvailableGeometries. In the following example, I'm looking for available geometries that are tagged `cartographic_boundary` and valid for the measurement `us.bls.avg_wkly_wage_10`. As expected, only one row is returned (Shoreline clipped US County).

```SQL
SELECT geom_name
FROM OBS_GetAvailableGeometries(ST_MakeEnvelope(-74, 41, -73, 40, 4326), '{boundary_type/tags.cartographic_boundary}','us.bls.avg_wkly_wage_10')
WHERE valid_numer is true
```
Output: Shoreline clipped US County

In this example, I look at all the available geometries and their geom_tags (which you can pass into `filter_tags`) for a small polygon in the United States:

```SQL
SELECT geom_name, geom_tags::text
FROM OBS_GetAvailableGeometries(ST_MakeEnvelope(-74, 41, -73, 40, 4326))
```

**Comment by ethervoid** [comment]
Te
