### ISSUE TITLE
Some measurement names are quite bad

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#180]
Come from the review made by @saleiva for the new DO UI.

Maybe Sergio could write here down more information about the problem

**Comment by michellemho** [comment]
I agree! I wrote up two tickets earlier about the problem of the volume and quality of measurement names:

https://github.com/CartoDB/bigmetadata/issues/169
https://github.com/CartoDB/bigmetadata/issues/168

**Comment by ethervoid** [comment]
Great! thank you! We should use this issue to have a list of issues about the measurement names in order to fix all of them at once :)

**Comment by saleiva** [comment]
Hard to do the list but CANADA ones are a good example of some that we should improve

**Comment by michellemho** [comment]
Agreed. You can also see that Australia and Brazil are also quite bad. I think the easiest and fastest way to fix this is to reduce the number of variables in these countries from _thousands_ to a few _hundred_, so we can ensure quality in names and descriptions. I can come up with a list to start; and get back to you guys for feedback.

**Comment by javitonino** [comment]
I'm closing this in favour of https://github.com/CartoDB/bigmetadata/issues/236, where we gather some more information. I'll keep #168 and #169 open and linked from the new one.
