### ISSUE TITLE
Canada NHS CMA data has change or the task is not working

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#195]
Re-executing the download of the Canadian NHS CMA data, I've found two issues with this dataset that make the task fail.

### File with "wrong" headers

Now there is a file called  `99-004-XWE2011001-201-DQ` which has the following content:
```csv
"Census Metropolitan Areas (CMAs) and Census Agglomerations (CAs) - Geographies which exclude National Household Survey data for one or more incompletely enumerated Indian reserves or Indian settlements"
"Geo_Code","Geo_Name","Geo_Type"
"421","Québec","CMA"
"462","Montréal","CMA"
"590","Sault Ste. Marie","CA"
"602","Winnipeg","CMA"
"935","Victoria","CMA"
```

`make -- run ca.statcan.data AllNHSTopics`

When the ETL tries to process that file, fails [here](https://github.com/CartoDB/bigmetadata/blob/master/tasks/ca/statcan/util.py#L262)

The error is: `ValueError: Invalid file: tmp/ca.statcan.data/DownloadData_cma_nhs_5600a4c4b1/99-004-XWE2011001-201-DQ.CSV^M`

### Data file with multiples parts for the same geocode
The data file called `99-004-XWE2011001-201` has some geocodes with what rows with the total data and parts for different zones, for example quebec and New Brunswick). Here a sample:
```csv
330,New Brunswick,Campbellton,CA,26.1,Income of individuals in 2010,  65 years and over (%),,30.1,,28.2,,31.5,
330,New Brunswick,Campbellton (New Brunswick part),CA,26.3,Income of individuals in 2010,  65 years and over (%),,30.1,,28.2,,31.5,
330,New Brunswick,Campbellton (Quebec part),CA,25.6,Citizenship,Total population in private households by citizenship,1,3165,,1500,,1665,
```

This makes that the `SplitAndTranspose` task generates a rows for every Topic with that geocode than includes the three parts and it fails to make the COPY to the database because it exceeds the number of columns.

The error is:
```
ERROR: ERROR:  extra data after last expected column^M
CONTEXT:  COPY copydatatotable_cma_census_t009_c52ae25de4, line 18: "330,15270,7215,8055,2595,1210,1380,12675,6005,6675,8325,4180,4145,1205,605,605,7115,3575,3540,6200,3..."^M
```

// @michellemho for awareness

**Comment by javitonino** [comment]
A quick way to run only the relevant part of the task: `make run-parallel -- ca.statcan.data NHS --resolution cma --topic t001`.
