### ISSUE TITLE
10 max measurements limit is not active 

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#199]
On the new Data Observatory UI we supposedly have a 10 measurements limit per analysis, but currently more that 10 measurements could be added and ran.

**Comment by xavijam** [comment]
That's a good one, we will limit it. Do you feel we should add it to response team? cc @jorgesancha

**Comment by juanignaciosl** [comment]
Uhm, I think that we could also add validation at backend. What do you think, @xavijam ?

**Comment by xavijam** [comment]
I feel it should be the proper solution, both limits. One in backend (camshaft?) and another in frontend.

**Comment by jorgesancha** [comment]
If we want to do immediately on frontend, response team might be the only option this week?

**Comment by juanignaciosl** [comment]
@xavijam as this is an analysis I think that we could check at Rails. _But_ I'm not sure if it's the most appropriate place. What do you think, @ethervoid ?

**Comment by ethervoid** [comment]
We could use the limit part of camshaft to check the number of elements but we should disable the option to create new elements in the UI when the number is 10

**Comment by juanignaciosl** [comment]
Ok, I see. cc @rochoa for awareness.

**Comment by rochoa** [comment]
_Playing devil's advocate here_: should we limit on the backend? I mean, if at backend I can concatenate two DO analyses with 10 measurements, why I shouldn't be able to have just one with 20 measurements?

**Comment by noguerol** [comment]
This restriction is based on the UI experience, so there is no need to force this too via API if there is no need.

**Comment by juanignaciosl** [comment]
So, we're going to focus on the UI limit, which is the actual blocking issue. @xavijam , can you prioritize this, please?

**Comment by nobuti** [comment]
Closed by https://github.com/CartoDB/cartodb/pull/12552
