### ISSUE TITLE
Limit measurement description size

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#200]
On the new Data Observatory, the new measurements dropdown shows the whole description, which in many cases overflows dropdown's height difficulting a lot going through them.
I recommend not the easy fix (limiting this via UI), because that will turn into a lot of measurements with cropped info, but to rewrite every measurement description that exceeds 100 characters.

**Comment by juanignaciosl** [comment]
Duplicated: #179.

**Comment by noguerol** [comment]
haha, I thought I erased this. Damn me.
