### ISSUE TITLE
Boundaries slider should not appear when only 1 boundary is available

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#202]
On the new DO UI, and from a UX perspective, the boundaries slider **should not** be rendered when only 1 boundary is available for that measurement, as it surely be confusing for the user. 
My suggestion is to only show the name of the boundary, with no slider.

![captura de pantalla 2017-07-21 a las 12 47 34](https://user-images.githubusercontent.com/70603/28460531-cbcce392-6e12-11e7-997f-55ee9dcced24.png)

cc @CartoDB/design for awareness.

**Comment by arianaescobar** [comment]
I completely agree. Give us a while to think about the correct visual way of showing that information in that scenario.

cc @saleiva for prioritizing

**Comment by saleiva** [comment]
directly to the first position of the backlog

**Comment by saleiva** [comment]
![screen shot 2017-07-24 at 16 00 36](https://user-images.githubusercontent.com/132149/28526965-74fc52fe-7089-11e7-8c9d-1b65491b98a2.png)

Updated in Builder - Analysis sketch file

**Comment by saleiva** [comment]
@noguerol moving this to the icebox until it gets implemented. Feel free to promote this to the main repo for attacking this.

**Comment by arianaescobar** [comment]
This also needs to be added to our toolkit, I opened a ticket for it last week: https://github.com/CartoDB/design/issues/902

**Comment by juanignaciosl** [comment]
@saleiva can you prioritize this at design, please?

**Comment by arianaescobar** [comment]
This is ready on our end @juanignaciosl. You can use the last mockup image uploaded by @saleiva.

**Comment by juanignaciosl** [comment]
Thanks, @arianaescobar !

@xavijam can you prioritize this, please?

**Comment by nobuti** [comment]
Closed by https://github.com/CartoDB/cartodb/pull/12547
