### ISSUE TITLE
Measurements descriptions UI overflow

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#205]
On the new DO UI, many measurements have descriptions that are not only big enough for not to be read but to overflow the dropdown height. We should not solve this the quick way (limiting via UI) but rewriting every long description to fit in a 100 char long string.

![captura de pantalla 2017-07-21 a las 13 07 08](https://user-images.githubusercontent.com/70603/28461146-8eace496-6e15-11e7-876f-ca686b3e9b58.png)

**Comment by juanignaciosl** [comment]
Isn't this the same as #200?
