### ISSUE TITLE
New DO UI caption fixes

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#207]
On the new DO UI there are several captions we should change: 

1. `Enrich from Data observatory` for `Select region`
2. `Define your input layer` for `For augmenting your layer`
3. `Base layer` for `Source`
4. `PICK AS MANY AS YOU WANT` for `PICK UP TO 10 MEASUREMENTS`
5. `Metric for normalization` for `Select a Metric`

**Comment by juanignaciosl** [comment]
@xavijam , can you prioritize this, please?
