### ISSUE TITLE
DMA (Television Market Areas) No longer available 

### ISSUE THREAD

**Issue by cartodave** [CartoDB/bigmetadata#223]
When doing the following Query: 

``` sh 
INSERT INTO dma_layer(the_geom, geom_refs)
SELECT *
FROM OBS_GetBoundariesByGeometry(
       ST_MakeEnvelope(-130.5883820057,24.686952412,-63.544921875,51.3744013929,
                      4326),
       'us.dma.the_geom')
```

the `us.dma.the_geom` boundary does not return anything. The query is correct if you change the boundary layer it will return correctly (for ex. states or counties). 

If this layer had changed would like to know the new layer reference. If it is no longer available, please update documentation here: 

https://cartodb.github.io/bigmetadata/united_states/boundary.html#television-market-area

**Comment by javitonino** [comment]
Blocked by https://github.com/CartoDB/cartodb-management/issues/4985

**Comment by cartodave** [comment]
Found out that DMA areas need to be removed due to a legal notice from Nielsen.

**Comment by juanignaciosl** [comment]
This is no longer blocked, I think.

**Comment by javitonino** [comment]
Closing, see linked ticket for solution.
