### ISSUE TITLE
Data Observatory Speed tests

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#224]
@kevin-reilly and I are lately getting constant timeouts / non resolved / or super long completion times in the new DO while performing some acceptance tests.

In my case, with this **250 POINTS** table I wasn't able to enrich it several times, and the successful ones lasted about 5 minutes.

[Random_US_Points.csv.zip](https://github.com/CartoDB/bigmetadata/files/1174331/Random_US_Points.csv.zip)

Kevin is getting similar results on his account.

We should research this prior public release and check if has something to do with our team account or on the contrary we are facing any other problem, in which case would be a priority fix.

**Comment by juanignaciosl** [comment]
I have just killed a couple of queries and a new analysis worked for that datsaset, and it didn't take too long (about half a minute).

1.- Which account is @kevin-reilly using?
2.- Could you please be more specific on the DO analysis that you set? Knowing the parameters of your analysis is important for us. Even though you experience that problem with every analysis, having at least one of you specific cases is really useful.

**Comment by kevin-reilly** [comment]
I am using the team account.

I have been trying a bunch of different data sets of varying sizes.

Right now I am testing with mlb_players which has ~20k records.

--
*Kevin Reilly*
SVP Product
*CARTO <https://carto.com/> | kevin@carto.com <kevin@carto.com>*
(917) 375-2168

**Comment by noguerol** [comment]
This is happening with every measure I tried, but we can use **US total population** as a reference. It seems the first time you run the analysis works, but it's always failing (not resolving, actually) when you start recalculating a measurement or you add another one, run the whole thing, then delete it and run it again. 
Actually I think the analysis is not even started, because no `Analysis [NODE] running` is notified, we are just getting the spinning confirmation button.

![image](https://user-images.githubusercontent.com/70603/28617753-05955ada-7202-11e7-84c4-ae9c0eb00522.png)

**Comment by noguerol** [comment]
I think I've nailed down one of the problems, that is happily related to https://github.com/CartoDB/bigmetadata/issues/215 . Analysis won't resolve when you ask for calculate a measurement that has been calculated in the past. I assume it's cached and because of that is not querying it again nor asking for the cached version.

**Comment by juanignaciosl** [comment]
Oh, great forensics, @noguerol  :-) We'll tackle this ASAP.

**Comment by ethervoid** [comment]
This is something we should investigate but we haven't change the way DO return data, we've been working in the public API part so the performance should be the same.

**Comment by noguerol** [comment]
This is probably related with the cache bug, so we can close it for the moment.
