### ISSUE TITLE
DO: Error augmenting with text columns

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#226]
_Just a pointer to CartoDB/camshaft/issues/315, as we should probably check this for DO public release._

cc @noguerol

**Comment by noguerol** [comment]
Damn, I also opened a ticket. We close this ir you're ok with that, as the other one keeps all the info.

**Comment by juanignaciosl** [comment]
Thanks! For future reference, this is the issue that @noguerol mentions: #227
