### ISSUE TITLE
Error augmenting with text columns

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#227]
Directly copied from: https://github.com/CartoDB/camshaft/issues/315

STR

1. Create an empty map
2. Create a point in Spain
3. Add a DO analysis, select "Proper name of prov" as the measure
4. Run the analysis
5. You get an error Analysis A1 failed: invalid input syntax for type numeric: "Toledo". This happens with both DO analyses (single/multi measure).

I have not confirmed this is a camshaft issue (it could be in the extension), but I feel like this is related to this numeric cast. In any case, more investigation is needed.

cc @juanignaciosl @javitonino

**Comment by javitonino** [comment]
Blocked by https://github.com/CartoDB/camshaft/issues/316. See rationale in that ticket.

**Comment by noguerol** [comment]
This is apparently unblocked on the Engine side, but @javitonino to confirm

**Comment by javitonino** [comment]
This is under CR at Engine. I will update to reflect it.

**Comment by ethervoid** [comment]
Deployed the fix and made the acceptance. It works now

**Comment by javitonino** [comment]
Working on team!
