### ISSUE TITLE
quickstart docs don't yield a running instance

### ISSUE THREAD

**Issue by contra** [CartoDB/bigmetadata#228]
Followed the quickstart docs on both a linux and an OSX machine, getting this on both:

```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "postgres" (172.17.0.4) and accepting
	TCP/IP connections on port 5432?

Makefile:137: recipe for target 'run' failed
```

Is there additional config needed?

**Comment by juanignaciosl** [comment]
No. Is that the only error message?

Could you please write to cartodb@googlegroups.com instead? Thanks!

**Comment by contra** [comment]
@juanignaciosl Yeah, this is the only error message.

Google groups? 🙁  Probably not. If you don't respond to issues here you can disable the issue tracker in the settings tab for a repository, btw: https://github.com/CartoDB/bigmetadata/settings

**Comment by juanignaciosl** [comment]
I suggested the mailing list because not only CARTO team but also community people help there, so it's the best place for questions.

We use the issue tracker, but not for questions (this _might_ be an actual problem, but it looks more like a configuration or platform issue).

**Comment by contra** [comment]
@juanignaciosl If the documentation for quick start doesn't yield a running instance I'd say that's a bug, either in the code or the docs - not a question.
