### ISSUE TITLE
DO documentation on existing datasets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#234]
- [ ] DO documentation on existing datasets
- [ ] Working check

**Comment by javitonino** [comment]
This is a first step: https://docs.google.com/a/cartodb.com/spreadsheets/d/1NfNOMcaIUAxz6Y1qwY28paZVHNqR1SrxavA_9pw1XhY/edit?usp=drive_web

But there is still much to do here.

**Comment by javitonino** [comment]
I think we can close this. We have pretty much everything working now, and the things that not have been ticketed (some final details regarding geonames).
