### ISSUE TITLE
Fix and improve UK

### ISSUE THREAD

**Issue by javitonino** [CartoDB/bigmetadata#253]
- [x] Download links are broken (they have broken links in the [census webpage](https://www.ons.gov.uk/census/2011census/2011censusdata/bulkdata/bulkdatadownloads)). [Alternative link](http://webarchive.nationalarchives.gov.uk/20140115215021/http://data.statistics.gov.uk/Census/BulkLocalCharacteristicsoaandinfo310713.zip)
- [x] Add [Scotland](https://github.com/CartoDB/bigmetadata/issues/58) and Northern Ireland data. Note that there are some jobs for Scotland already in the code.
- [x] Add Total Male/Female population https://github.com/CartoDB/observatory-extension/issues/169
- [ ] Add geonames

**Comment by javitonino** [comment]
Reopening for pending tasks

**Comment by javitonino** [comment]
After dancing around this, trying to extract common data from three censuses (EnglandWales, Scotland, Northern Ireland), I found a different release with more unified data: https://www.nomisweb.co.uk/census/2011/all_tables?release=UK.2

I'll be redoing a fair chunk of the tasks to use the new datasource while keeping the current ids, which will be completely different. I'm also documenting some problems with our approach to some of this data, so hopefully we can do better in the future.

I'll keep you posted.

**Comment by javitonino** [comment]
Summary of all data in UK, and my suggested fixes:

**Age**
We have multiple sets of overlapping age groups:
1. 0-24, 25-49, 50-64, 65-74, 75+
2. 3+, 3-15, 16-49
3. 16+

My suggestion is to keep it as it is, as most fields are in use. We should avoid this in the future, and eventually deprecate it in favour of something more uniform (5-year buckets?).

**Sex**
Not present: add it.

**Language**
- England/Wales -> Available
- Scotland -> Not available, it is not present in census survey
- Northern Ireland -> Available with different classifications than EW, more generic. The full-detail version is only available for the whole NI.

I would delete it. It has not been used, there is no data for Scotland, and the NI is not very useful. We could also go with partial coverage (only England + Wales).

**Religion**
- England/Wales -> Available
- Scotland -> Available, they even publish a table with the same schema as EW for compatibility.
- Northern Ireland -> Available with different classifications than EW, more generic. The full-detail version is only available for the whole NI.

I would delete it, as it is not in use and we cannot give full coverage. We could ask NISRA (NI census agency) for a table (https://www.nisra.gov.uk/publications/census-commissioned-output) but it would probably be rejected due to statistical secrecy. We could also go with partial coverage (excluding NI).

**Ethnic**
Available for the whole UK

**Place of birth**
Available for the whole UK

**Health**
Available for the whole UK

**Economical activity**
Available for the whole UK

**Comment by antoniocarlon** [comment]
**Acceptance:** executed the UK tasks in the new ETL machine. Everything worked fine and the output tables seem to be correct.

**Comment by javitonino** [comment]
In production.
