### ISSUE TITLE
Go public with new DO

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#258]
This is a final mark for deployment.

Currently it depends on the following issues:
- [x] CartoDB/cartodb/issues/12648
- [x] CartoDB/cartodb-platform/issues/3547

We'll close this issue when it's released.

@gregsundermann , you'll be notified when this is public.

**Comment by juanignaciosl** [comment]
@noguerol we're ready to make DO improvements public. It's a matter of minutes (enable FF and change the pointer to the DO DB). We'll wait for your green light :)

**Comment by noguerol** [comment]
Official communication will be next Tuesday 5th, so that is the day we activate it 🎉

Mailing will be sent in the morning EST time so we should do the deploy and flag activations some time before (Madrid time morning, iow)

**Comment by juanignaciosl** [comment]
Deployed! cc @noguerol @gregsundermann

**Comment by noguerol** [comment]
This is epic, mates <3
