### ISSUE TITLE
target fr-all fails

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#263]
target `make fr-all` fails:
 - DownloadUnzipFR
 - RawFRData

Related to #161

**Comment by antoniocarlon** [comment]
The data from insee has changed and there are new sources with completely different file formats. We will need to rewrite the ETL for France.

Also, we will need to take a look at the license https://www.insee.fr/en/information/2409139

**Comment by javitonino** [comment]
2012 data can be found [here](https://www.insee.fr/fr/information/2882311). We want the last column of the table (Bases infracommunales). My very rusty french is getting some use 🙌

**Comment by antoniocarlon** [comment]
Updated and importing like a charm. @javitonino your french is much better than mine.
Created the issue #273 for importing new datasets
