### ISSUE TITLE
getting nulls for B25075025_quantile

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/bigmetadata#30]
While creating tests for observatory-extension, I got null values for `B25075025_quantile` returned from the test point centered on CartoDB's Bushwick office. Previously tests gave back `0`.

cc @talos

**Comment by talos** [comment]
Interesting.

```
SELECT obs_getmeasure(
  st_setsrid(st_geomfromtext('POINT(-73.936669 40.704512)'), 4326),
              'us.census.acs.B25075025_quantile')
```

Or any other quantile column works fine on envisage (returning 0 or a non-0 numeric) but returns NULL for everything on the team account.

**Comment by talos** [comment]
This may be because the block-group level quantile table uploaded in the dump had length 0...

**Comment by talos** [comment]
I've generated a new dump with the empty table replaced.  We'll see if this fixes the problem.

**Comment by talos** [comment]
Confirmed fixed (returns 0 on team account).
