### ISSUE TITLE
Use a helper to manage file downloads

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#301]
Use a helper to manage file downloads instead of implementing a download mechanism for each task.

Avoid downloading files using `wget` or `curl` (rely on requests instead).

Also, from https://github.com/CartoDB/bigmetadata/pull/298 :
 - gunzip could be done with gzip library
 - cut could be done with split
 - copy command could be achieved with psycopg2

**Comment by javitonino** [comment]
This is a dupe of https://github.com/CartoDB/bigmetadata/issues/255. Migrating this checklist to that one since it's more complete.
