### ISSUE TITLE
wrong value naming for total popultation raw data 

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/bigmetadata#310]
I think it is confusing naming `per_sq_km` the value:

![image](https://user-images.githubusercontent.com/5215798/30166003-4c05becc-93e2-11e7-9fcd-87bc025bcbb4.png)

This should be fixed.

**Comment by ramiroaznar** [comment]
I have checked other measures, and it is happening everywhere.

**Comment by javitonino** [comment]
Aside from this, it would be nice to write a query to `UPDATE` a table, so as many people use DO by copying the data into their table.
