### ISSUE TITLE
Take a look at the shoreline clipping for TIGER

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#314]
Take a look at the shoreline clipping algorithm used in TIGER. The algorithm is described [here](https://carto.com/blog/tiger-shoreline-clip/)

**Comment by antoniocarlon** [comment]
Taking a look at the shoreline clipping for Tiger, it seems that the process works reasonably well. It breaks the geometries into manageable chunks using `ST_Subdivide` and performs the unions and differences only for the affected geometries to avoid excesive memory consumption. It also uses spatial indexes for the intermediate tables.

The `GROUP BY` part of the `JoinTigerWaterGeoms` task is legit as the query performs a cartesian product of the geometries from `SplitSumLevel` and `SimpleShoreline` that intersect, and the `GROUP BY` part allows the use of `ST_Union` on a geometry collection. The result of `JoinTigerWaterGeoms` is a table with two geometric columns. For each file, the first column is the positive chunk and the second column is the union of the negative chunks that affect the positive chunk (the `DiffTigerWaterGeoms` task calculates the difference in the next step).

The only possible issue with the water bodies is that, for State and County levels, they are not taken into account when they intersect a given landmask (a low resolution geometry that defines the inner -no close to water- part of the US). In this picture, the orange line represents the landmask, the green geometries are the ones taken into account and the red ones are the ones filtered out by the landmask. Anyway, this sould not be a problem for DO:

![screenshot from 2017-09-19 16-53-14](https://user-images.githubusercontent.com/6155203/30600671-609622d2-9d60-11e7-837a-9813c477c47e.png)

**Comment by ethervoid** [comment]
Good for more moreover we have improved the "problematic" query #315 so we could move on in this part I think
