### ISSUE TITLE
Dump with simplified tables

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#341]
Generate a dump with simplified tables

**Comment by ethervoid** [comment]
Please give me a hint of the acceptance must steps for this issue

**Comment by antoniocarlon** [comment]
We could use some existing data and augment it with DO in production and team and compare the results (the numbers will differ but we don't expect huge differences or new nulls)

**Comment by javitonino** [comment]
I borrowed some datasets to test. Very good results, in all cases the accuracy drop was under 0.1%, and there was no difference in number of NULLs.

Maximum error per row for the tested datasets
Spain / Line 5 closure map - 0%
USA / Missouri education map - 0.04%
UK / Referendum vote segments - 0.007%
FR / Logistics - 0.0005%
