### ISSUE TITLE
Remove MX NULL columns

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#348]
In MX there are some columns with only NULL values for low level geographies. We need to remove them.

Related to https://github.com/CartoDB/bigmetadata/pull/337
See https://github.com/CartoDB/bigmetadata/pull/337#issuecomment-335511353

**Comment by ethervoid** [comment]
Wait until the ETL machine is free

**Comment by ethervoid** [comment]
### Acceptance

I've generated some stats for the MX data with this query:

```sql
copy (select 'analyze observatory.' || tablename || '; copy (select ''' || id || ''' as table, tablename as id, attname, null_frac from pg_stats where schemaname = ''observatory'' and tablename = ''' || tablename || ''' and null_frac >= 0.25) to program ''cat >> /tmp/null_queries.csv'' CSV;' from observatory.obs_table where id ilike 'mx.inegi.tasks_mx_inegi_census%') to '/tmp/null_queries.sql';
```

Here is the result of that query [null_queries.sql.zip](https://github.com/CartoDB/bigmetadata/files/1418776/null_queries.sql.zip)


This query generates SQL statements in a file that once executed allows us to get what columns of tables have more or equals than a 25% null values. Here is the result [null_queries.xls.zip](https://github.com/CartoDB/bigmetadata/files/1418770/null_queries.xls.zip)

As a sneak peak, we have columns with a 44% of NULL and all the columns that surpasses the 25% of NULLS are in `manzana` and `ageb` boundaries.

From my point of view, we can reduce more the amount of nulls so I'd try including this exceptions

**Comment by antoniocarlon** [comment]
Taking a look at this stats, it seems that in these cases we don't want to remove the columns with `NULL` values but replace the `NULL`s with `0`

**Comment by ethervoid** [comment]
Ok, si move it to develop or we deploy this?

**Comment by antoniocarlon** [comment]
Currently we have it deployed with `NULL`s. I have just created a new issue (#362) to address this so I would deploy this in the current state and redeploy when we solve the new issue

**Comment by ethervoid** [comment]
Ok good for me
