### ISSUE TITLE
Update Data: US Bureau of Labor Statistics

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/bigmetadata#349]
The US Bureau of Labor Statistics (QCEW) has released data through 2017Q1. Ours is currently only up to 2015Q4. 

This has been requested by a user

**Comment by hannahblue** [comment]
@javitonino You mentioned this should be relatively low effort, right? 

cc @juanignaciosl

**Comment by javitonino** [comment]
They have kept the same data format for the last few years. I'm assuming they have not suddenly changed it for 2017. If my assumption holds, it should be a very quick change (just adjust some constants).

**Comment by hannahblue** [comment]
Sounds good, thanks

**Comment by antoniocarlon** [comment]
**Note for the acceptance:** `make us-bls` will import all BLS data up to 2017Q1
