### ISSUE TITLE
UK fixes (bis)

### ISSUE THREAD

**Issue by javitonino** [CartoDB/bigmetadata#354]
Health tables (QS302/303UK) should have total population as denominator (as opposed to population 3 and over). This changed when we changed the data source from wales to UK.

Take the chance to quickly review other tables, you can take a look at the expected denominator in teh table metadata -> https://www.nomisweb.co.uk/census/2011/qs303uk

**Comment by antoniocarlon** [comment]
**Note:** some denominators will be missed until #364 is solved
