### ISSUE TITLE
The shoreline clipping algorithm is generating artifacts

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#356]
The shoreline clipping algorithm is generating slender artifacts. For example in Alaska:

![screenshot from 2017-10-23 16-46-45](https://user-images.githubusercontent.com/6155203/31895558-cb582fa4-b811-11e7-970f-29a427e95892.png)

It can also be seen in the blog entry that explains the shoreline clipping proccess (https://carto.com/blog/tiger-shoreline-clip/):

![screenshot from 2017-10-23 16-48-12](https://user-images.githubusercontent.com/6155203/31895629-fb045fe8-b811-11e7-95e7-352216d107af.png)

We need to refine the clipping algorith to avoid this kind of artifacts.

**Comment by antoniocarlon** [comment]
One possible approach could be removing very slender features, with slenderness defined as the relation between perimeter and area.

**Comment by antoniocarlon** [comment]
The artifacts aren't independent features but parts of existing ones (forming a multipart feature). The simplification mechanism removes the least significant points of the geometry (with the minimum effective area because we are using the Visvalingam-Whyatt algorithm), so these points are removed first. Thus the simplification proccess also leaves the geometry clean of all these artifacts.

Non simplified layer (PUMA):
![screenshot from 2017-10-31 10-05-35](https://user-images.githubusercontent.com/6155203/32215742-1ed7fb66-be23-11e7-9484-5cf8197d7a82.png)

Simplified layer (PUMA):
![screenshot from 2017-10-31 10-05-58](https://user-images.githubusercontent.com/6155203/32215751-225995d8-be23-11e7-8f3a-8319d64c7520.png)

**Comment by javitonino** [comment]
Does this work for all geometry levels? I'm guessing yes. In that case, I think we can close this for now, and only revisit it if we finally back down of simplification (which looks unlikely).

**Comment by antoniocarlon** [comment]
Yes, both simplification mechanisms (Mapshaper and PostGIS) solve the artifacts problem because we are using the Visvalingam-Whyatt algorithm in both cases, so we can close the issue and reopen it if needed
