### ISSUE TITLE
User/Partner request: Japan data sets

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/bigmetadata#360]
AIG, EY, and Pacific Spatial Solutions have identified demand for data for Japan such as census, environmental, and points of interest. Full list of requested sources here: 
https://docs.google.com/a/cartodb.com/document/d/1Sy2QXtAzZtSCmtQdpEt62Edt7psLrFLeNah18Zvh5J0/edit?usp=sharing

cc @fernando-carto

**Comment by fernando-carto** [comment]
Thanks, Hannah. I'll update the list in case of new sources

**Comment by hannahblue** [comment]
Additional sources:

NTT Docomo (https://www.nttdocomo.co.jp/corporate/disclosure/mobile_spatial_statistics/). Near also has their own location data (https://near.co/datastories/). 

You may be able to use this service. https://opendata.resas-portal.go.jp/  They have their API.

This is the Japanese census data. https://www.e-stat.go.jp/gis

**Comment by hannahblue** [comment]
Pacific Spatial has prepared some data. I haven't looked at it yet https://drive.google.com/open?id=1GKdIp8D_uds_4Td9F_f4gL9kWRSeussrsy_uKwtOxSM
