### ISSUE TITLE
Check the nulls of MX and replace them with 0 if needed

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#362]
Check the "almost NULL" columns found in MX (see https://github.com/CartoDB/bigmetadata/issues/348) and replace the NULLs with 0 where it makes sense

**Comment by antoniocarlon** [comment]
The value `-6` is decoded to `NULL` in the ETL task and this is the cause of the high percentage of `NULL`s in the output tables. I have searched through the INEGI webpage (SCINCE data dictionary and other sources) and I haven't found any reference to this `-6` value for absolute measurements (or the `-8` value for relative measurements) found in the downloaded data.

The source data cointains also values that are `0` so this `-6` may mean some kind of "no data" or "refuse to answer" but I can't find any reference to it. Anyway, as the data has also `0`s in the values, it doesn't make sense to translate this `NULL`s to `0`s.

**Comment by javitonino** [comment]
👍 

A pity that we were not able to find the definition, but it seems like data missing is the more logical explanation. We can consider removing the columns if there are too many nulls, but that's a story for another time.
