### ISSUE TITLE
Change the names of columns that have a number at the start 

### ISSUE THREAD

**Issue by stuartlynn** [CartoDB/bigmetadata#4]
Importing the observatory data in to CartoDB or any other database using CSV or even JSON often ends up with column names that look like this : 

<img width="901" alt="screen shot 2016-03-16 at 11 07 27 am" src="https://cloud.githubusercontent.com/assets/209838/13817137/822636b4-eb67-11e5-9033-eb31f993fc6f.png">

The first number gets truncated off. Can we name columns like 100_000_to_124_999_in_households something like income_100_000_to_124_999_in_households to avoid this issue and to make them a little easier to read?

**Comment by talos** [comment]
this is no longer how we do it!
