### ISSUE TITLE
`suggested_name` same for same numerator with different denominators

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/bigmetadata#418]
An issue that crops up when augmenting from the same numerator with different denominators, is the DO suggests the same column name, as you can see in the JSON metadata sent through to `OBS_GetData`.

For example, you can get this from `OBS_GetMeta` with region=Mexico, keywords='education', boundaries='mx.inegi.municipio':
```json
[
    {"index":14,"denom_aggregate":"sum","denom_colname":"employed_incomplete_secondary_education","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO13","denom_name":"Employed population with incomplete secondary education","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":1,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":1},
    {"index":15,"denom_aggregate":"sum","denom_colname":"female_employed","denom_description":null,"denom_geomref_colname":"cvegeo","denom_id":"mx.inegi_columns.ECO5","denom_name":"Employed female","denom_reltype":"denominator","denom_t_description":null,"denom_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","denom_type":"Numeric","geom_colname":"the_geom","geom_description":"","geom_geomref_colname":"cvegeo","geom_id":"mx.inegi.municipio","geom_name":"Municipios","geom_t_description":null,"geom_tablename":"obs_366a1365508f0a27c925858ba2afb2d09884e576","geom_timespan":"2015","geom_type":"Geometry","id":10,"max_score_rank":null,"max_timespan_rank":null,"normalization":"denominated","num_geoms":5.8725732755,"numer_aggregate":"sum","numer_colname":"female_employed_incomplete_secondary_education","numer_description":null,"numer_geomref_colname":"cvegeo","numer_id":"mx.inegi_columns.ECO14","numer_name":"Employed female population with incomplete secondary education","numer_t_description":null,"numer_tablename":"obs_bbbeed134ba68308a4fac833514e6b7a5e5bdf11","numer_timespan":"2010","numer_type":"Numeric","score":36.600226087,"score_rank":1,"score_rownum":2,"suggested_name":"female_employed_incomplete_secondary_education_rate_2010","target_area":null,"target_geoms":null,"timespan_rank":1,"timespan_rownum":2}
]
```

Creating the same analysis through Builder, the analysis 'Apply' button becomes inactive if I choose numerator / denominator combos like above:

<img width="321" alt="screen shot 2018-02-21 at 16 16 43" src="https://user-images.githubusercontent.com/1041056/36507208-0767ace4-1727-11e8-891c-9e023e5b5b10.png">

If I augment through the SQL API, CARTO doesn't complain that there are two columns of the same name, but only returns one of the columns. So users are not getting back all the data they request. I should probably add a check in cartoframes about this and update the column names as a workaround.

From CartoDB/cartoframes#323

cc @hannahblue 

_Edited to make the issue clearer_

**Comment by juanignaciosl** [comment]
Thank you for the detailed explanation :-)

We're going to change from a "numerator + 'rate' + timespan" naming schema to a "numerator + timespan + 'by' + denominatr" naming schema. That way we get rid of most collisions. Timespan is going to be moved just after the numerator instead of at the end because we'll hit the 63 char limit sooner, due to the denominator, and we don't want collisions when a user imports several timespans.

How does it sound?

**Comment by andy-esch** [comment]
Super, and apologies on the badly written initial issue!

> "numerator + timespan + 'by' + denominator"

That sounds good to me, but I wonder how often the 63 character limit will be exceeded?

For Mexico, this is what the distribution of lengths looks like:

![colname_lengths](https://user-images.githubusercontent.com/1041056/36542920-3a6d9cbe-17b0-11e8-9711-47be49dcee70.png)

That's about 8% above 63 lines.

Here's the script:

```python
%matplotlib inline
import cartoframes
import pandas as pd
import matplotlib.pyplot as plt

cc = cartoframes.CartoContext(
    base_url='https://{username}.carto.com/'.format(username='eschbacher'),
    api_key='abcdefg')

# get roughly all mexican data obs metadata
meta = cc.data_discovery(region='coordsmetro_demo')

# create proposed suggested_colnames
out_colnames = meta.apply(
    lambda r: '%s_%s_by_%s' % (r['numer_colname'], r['numer_timespan'], r['denom_colname']),
    axis=1)

plt.hist([len(c) for c in out_colnames], bins=25)
plt.axvline(63, color='r', linestyle='dashed', linewidth=1)
plt.xlabel('length of colname')
plt.ylabel('number of occurrences')
print('Percent above 63 lines: {}'.format(
    100.0 * sum([len(c) > 63 for c in out_colnames]) / len(out_colnames)
))
```

**Comment by andy-esch** [comment]
Of course not everything has a denominator, so that's not a perfect analysis.

**Comment by juanignaciosl** [comment]
Thank you for the analysis and the code 😍 . One of my year resolutions is adding this to my toolbox by learning from you 😊 

I'm not worried about the suggested names that are beyond 63 characters, because we're going to trim those names. The actual concern is _how many of them would cause collisions after trimming_. From that 8%, only those denominators that begin with the same characters will cause collisions, and only when they're used with the same measurement and timespan. I think that this is a bit improvement. as we're going to have much fewer collisions than now (because now we're just appending `_rate`).

**Comment by ethervoid** [comment]
Didn't we close this issue?

**Comment by juanignaciosl** [comment]
@ethervoid it's not yet merged: CartoDB/observatory-extension/pull/327 .

**Comment by juanignaciosl** [comment]
Already deployed 🙌

**Comment by andy-esch** [comment]
Great!! cartoframes’ CI noticed yesterday :)  https://github.com/CartoDB/cartoframes/pull/433
