### ISSUE TITLE
Repository for DO ETL files

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#428]
Currently, ETL depends upon 3rd party files. If they change (see #427), running fails. We should create a file repository for the ETL so repeatability is guaranteed. It should, at least...
- store the last version that worked ("development branch").
- be able to store the tuple (extension version, ETL version, data): that would make the dump reproducible.

Let's discuss implementation alternatives, @ethervoid @antoniocarlon

**Comment by ethervoid** [comment]
PR #440
