### ISSUE TITLE
Update eurostat to add last changes

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#434]
Doing #426 I've found that all the `dic` files we have and the metabase.txt file are out of date so we need to update them to reflect the last changes.

- [x] Update dic files from [here](http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=dic%2Fall_dic.zip)
- [x] Update metabase.txt file from [here](http://ec.europa.eu/eurostat/estat-navtree-portlet-prod/BulkDownloadListing?sort=1&file=metabase.txt.gz)
- [x] Check how the table_dic.dic file is generated
- [ ] Execute eurostat to check for possible errors **<-- Acceptance?**

**Comment by antoniocarlon** [comment]
- The metabase table is downloaded when the ETL tasks are executed using the `DownloadMetabase` task and imported to a table using the `MetabaseTable`

(updating...)
