### ISSUE TITLE
Source not available for Canada boundaries in the DO catalog

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#500]
The Canada boundaries show _Not available_ as _Source_ in the DO Catalog (it would be nice to take a look at the _License_ field too).

Example: https://cartodb.github.io/bigmetadata/ca/boundary/ca.statcan.geo.cd_.html

**Comment by antoniocarlon** [comment]
@ramiroaznar RT, please?

**Comment by ramiroaznar** [comment]
How is this catalog generated? Is this a backend or frontend issue?

**Comment by antoniocarlon** [comment]
We need to take a look at the DO ETL tasks and Catalog generation. This is a backend issue

**Comment by ramiroaznar** [comment]
Should we close this one too?
