### ISSUE TITLE
Add more boundaries for the current countries

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/bigmetadata#503]
Based on the recent work we're doing to server MVT tiles we found that we need more boundaries for some countries in order to have better aggregation and granularity for different zoom levels.

The ideal situation is to get boundaries that match for Tiger levels State, county, census_tract, block_group and block

* **UK**
  In UK we only have the CDRC boundaries but we should add more like for example country level

* **Spain**
  We only have the INE census parts but we could add State (country/admin0), Autonomous regions (county), Provinces and census

More to check in the future

**Comment by juanignaciosl** [comment]
@ethervoid @antoniocarlon is there any current request or known need? As this issue is quite broad, it'd be great if we could make a breakdown of needed tasks.

**Comment by antoniocarlon** [comment]
AFAIK, ATM only this is needed https://github.com/CartoDB/bigmetadata/issues/568
Closing this!
