### ISSUE TITLE
Sample MC US data with Boundaries in Premium Data Library

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/bigmetadata#517]
@juanignaciosl, as discussed let's load some of the Mastercard data with boundaries for the US into the Premium Data Library for the team to access for demos.

**Comment by juanignaciosl** [comment]
@hannahblue do you want sparse data of the US at all zoom levels?

cc @ethervoid @antoniocarlon

**Comment by hannahblue** [comment]
That would be good unless it's too much (in terms of effort or size). Could do just a few cities and/or just blocks if that's easier.

**Comment by hannahblue** [comment]
@antoniocarlon, since slack is down I respond to you here. The sample you sent looks good 👍

**Comment by hannahblue** [comment]
@antoniocarlon, as discussed please add MC data for Cleveland for March 2013 and March 2016, and grant access to @StevePIsaac

**Comment by juanignaciosl** [comment]
Added to "Next" in Data team kanban because this should take <1h cc @luisbosque .

**Comment by antoniocarlon** [comment]
@hannahblue done! I have granted access to both @StevePIsaac and you.
You should be able to access it using the "Data Library" link in your dashboard.
If you find any problem, please reopen the issue.

**Comment by hannahblue** [comment]
Thanks @antoniocarlon!! 🎉
