### ISSUE TITLE
Request for MRLI Data into `hollyorr` Builder account

### ISSUE THREAD

**Issue by alissarose** [CartoDB/bigmetadata#587]
Hello Team!

We've got Bloomberg interested in the MRLI data and want to provide a sample via @orrholly 's builder account.

A few questions:
1. Do you have the USA MRLI data going back to 2012 ready to share via Premium Data Library?

wait, that's the only question 😅 -- so if the answer is **yes** -- plz grant `hollyorr` in the CARTO org access to the entire dataset for the US 2012-present 🙏 

tyty (for reference, this ticket https://github.com/CartoDB/CARTO-Geographica-Services/issues/130)

**Comment by alissarose** [comment]
pinging @rochoa @danicarrion @juanignaciosl  because I'm not sure who's roof it falls on to field these requests -- or if this is even the best place to do it. please advise 🙏

**Comment by jeffkaplan88** [comment]
Re-pasting this here for immediate steps forward ...

If I understand correctly, Raul identified this as the fastest (though very imperfect) path for getting MC data into Bloomberg
s hands ...

(1) We give them the CSV files for all US data back to 2012 (with GEOIDs but no geometries)
(2) We point them to the geometries available in the US Census website for them to join them based on the GEOIDs (explaining we have only joined them in the context of creating the MVT tiles for the app which won't be useful for them yet)

==> Does this make sense? Anything else we can do right now in terms of the data (or delivery of it) that would help them?  eg, Is CSV the only format it can be delivered in? 

==> One other question is whether there is any value in adding those CSV files to a cloud account?  If that data has GEOIDs only, is there any usefulness they might get from having it in a cloud account?

**Comment by alissarose** [comment]
closing as there's a separate email chain going on this
