### ISSUE TITLE
Errors at DO measures for '2010 - 2014'

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#609]
Reported by @andy-esch : 

--

i'm getting some errors on the cartoframes CI for DO operations that have been woking for the last 9 months or more. the issues specifically seems to be on DO measures for '2010 - 2014'. i get 438 measures for '2011 - 2015' and only 2 for '2010 - 2014' (the spielman singleton segmentation measures). was there a job gone wrong that prevented the 2010 - 2014 data from being loaded or something?

```
SELECT * FROM OBS_GetAvailableNumerators(
  ST_MakeEnvelope(-74, 41, -73, 40, 4326), NULL, NULL, NULL, '2010 - 2014')
WHERE valid_timespan IS True
```

that gives two rows
while this gives 438:

```
SELECT * FROM OBS_GetAvailableNumerators(
  ST_MakeEnvelope(-74, 41, -73, 40, 4326), NULL, NULL, NULL, '2011 - 2015')
WHERE valid_timespan IS True
```

--

cc @javitonino

**Comment by javitonino** [comment]
Wonderful. We have eaten the following ACS data with potatoes:
```
 2006 - 2010
 2014 - 2014
 2010 - 2014
 2010 - 2010
```

So 2010 and 2014, with 1 and 5 year samples.

It was removed here: https://github.com/CartoDB/bigmetadata/commit/fc08662f4b640a22e18a233ca4a463e5faf3983b#diff-9f22fdc12ce3a12b6faa5a759de5d366L35

@ethervoid do you remember why this was removed?

**Comment by javitonino** [comment]
We forgot to merge a branch that fixed it. Merged and rerunning.

**Comment by javitonino** [comment]
Executed successfully in production. Ready to ship.
