### ISSUE TITLE
Deploy 8/11 dump

### ISSUE THREAD

**Issue by talos** [CartoDB/bigmetadata#76]
Dump URL is:

s3://cartodb-observatory-data/do-release-2016_08_11_88ac0995eb/obs.dump

Passed tests on ETL test box with the latest version of the extension.

**Comment by talos** [comment]
@ethervoid Would be great to get this scheduled.

**Comment by ethervoid** [comment]
Ok, I want to deploy it with the changes of the tests you made. Tomorrow I'll try to have it deployed

**Comment by talos** [comment]
Beautiful, thanks.

**Comment by rafatower** [comment]
can this be closed?

**Comment by ethervoid** [comment]
Yup, closing
