### ISSUE TITLE
Auto-build docs on readthedocs

### ISSUE THREAD

**Issue by talos** [CartoDB/bigmetadata#78]
We need a post-commit hook setting to rebuild our docs at http://bigmetadata.readthedocs.io/en/latest/ .

@luisbosque happy to talk details over Slack.

**Comment by talos** [comment]
@rochoa Would it be possible to set this up?

**Comment by rochoa** [comment]
@talos I activated the ReadTheDocs Github's integration. Let me know if that suffice your requirements.

**Comment by talos** [comment]
Yup, this works.  Closing.
