### ISSUE TITLE
sample coordinates not within Spanish boundaries

### ISSUE THREAD

**Issue by michellemho** [CartoDB/bigmetadata#86]
example:

INSERT INTO {new_table_name} (the_geom, {geo_id_column})
  SELECT *
  FROM OBS_GetBoundariesByGeometry(
    ST_Buffer(CDB_LatLng(40.7, -73.9), 0.01),
    'es.cnig.prov'
  )

**Comment by talos** [comment]
All catalog sample points are now localized to the measure!
