### ISSUE TITLE
Spanish Census data returning NULL values

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/bigmetadata#94]
While [testing DO functions for Spanish data](https://github.com/CartoDB/solutions/issues/323), I found that a varying number of null values is returned for certain measures. 

Specifically, using `OBS_GetMeasureById()` with `es.ine.the_geom` boundaries from Madrid Metropolitan area. Table [here](https://team.carto.com/u/ernestomb/tables/mad_obs)

I have tried to summarize those results with the following workflow: 

1 - Write a query to find the number of _NULL_ values returned over a sample of 100 random values from the table above, for a specific measure: 

``` sql
SELECT count(*) FROM (
  SELECT
      OBS_GetMeasureById(
        geom_refs,
        'es.ine.t11_15',
        'es.ine.the_geom'
      ) as obs
  FROM (SELECT * FROM mad_obs ORDER BY random() LIMIT 100) as random100
  ) as foo
WHERE obs IS NULL
```

2 - Get a list of measures available for Spain. Only those coming from INE: 

``` sql
INSERT INTO obs_tables_spain (measure_id, description) SELECT id, name FROM OBS_Search('') WHERE id LIKE '%es.ine.t%'
```

3 - Write a function to summarize the results for all `es.ine.*` tables

``` sql
CREATE OR REPLACE FUNCTION obs_test() RETURNS integer AS $$
DECLARE 
  tabrow obs_tables_spain%ROWTYPE;
  null_count integer;
BEGIN
  FOR tabrow IN SELECT * FROM obs_tables_spain ORDER BY measure_id LOOP

    SELECT count(*) FROM (
      SELECT
        OBS_GetMeasureById(
          geom_refs,
          tabrow.measure_id,
          'es.ine.the_geom'
        ) as obs
      FROM (SELECT * FROM mad_obs ORDER BY random() LIMIT 100) as random100) as foo
    WHERE obs IS NULL
    INTO null_count;

    UPDATE 
      obs_tables_spain 
    SET nulls_over_100=null_count
    WHERE obs_tables_spain.cartodb_id=tabrow.cartodb_id;   

  END LOOP;

  RETURN 1;

END;
$$ LANGUAGE plpgsql;
```

The results are showing a high number of _NULL_ values returned for some tables. Check the complete results in [this table](https://team.carto.com/u/ernestomb/tables/obs_tables_spain) 

What do you think about all this @talos ? 
Maybe this is not the best way to check the DO functions, or maybe doing the automated test like this does not make sense at all 😂 . In any case, I would appreciate your point of view about all this

Thanks!

cc/ @jsanz @michellechandra

**Comment by talos** [comment]
This is to be expected -- at the seccion censal level, there are quite a few empty values.
