### ISSUE TITLE
Update name and logo on cover of Data Observatory PDF

### ISSUE THREAD

**Issue by csobier** [CartoDB/bigmetadata#99]
The Data Observatory PDF still shows the old logo. @talos , I know I mentioned this awhile ago but any chance you can update the name and logo?  (Marketing is asking me why this wasn't changed)

http://data-observatory.s3.amazonaws.com/observatory.pdf

**Comment by talos** [comment]
The PDF is clunky and difficult to work with due to its size.

We're moving over towards suggesting people use the [GitHub site](https://cartodb.github.io/bigmetadata/) until the docs are integrated.

I can get the PDF image updated next sprint.

**Comment by csobier** [comment]
I personally don't think it's a showstopper but Marketing came to me today and asked.  Thank you!

**Comment by talos** [comment]
This was resolved.
